/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Feb 24 18:30:18 GMT 2020
 */

package org.apache.commons.math4.stat.inference;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class BinomialTest_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.apache.commons.math4.stat.inference.BinomialTest"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "/var/folders/9c/2fm2fk412pj9zjkzvdx9w2fr0000gn/T/"); 
    java.lang.System.setProperty("user.country", "BR"); 
    java.lang.System.setProperty("user.dir", "/Users/joaocorreia/commons-math"); 
    java.lang.System.setProperty("user.home", "/Users/joaocorreia"); 
    java.lang.System.setProperty("user.language", "pt"); 
    java.lang.System.setProperty("user.name", "joaocorreia"); 
    java.lang.System.setProperty("user.timezone", "America/Sao_Paulo"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(BinomialTest_ESTest_scaffolding.class.getClassLoader() ,
      "org.apache.commons.numbers.gamma.RegularizedBeta$1",
      "org.apache.commons.numbers.fraction.ContinuedFraction",
      "org.apache.commons.statistics.distribution.DistributionException",
      "org.apache.commons.math4.exception.MathIllegalStateException",
      "org.apache.commons.numbers.fraction.FractionException",
      "org.apache.commons.math4.exception.NumberIsTooSmallException",
      "org.apache.commons.math4.exception.util.Localizable",
      "org.apache.commons.numbers.gamma.InvGamma1pm1",
      "org.apache.commons.numbers.gamma.GammaException",
      "org.apache.commons.math4.exception.util.LocalizedFormats",
      "org.apache.commons.statistics.distribution.SaddlePointExpansionUtils",
      "org.apache.commons.statistics.distribution.DiscreteDistribution",
      "org.apache.commons.statistics.distribution.AbstractDiscreteDistribution",
      "org.apache.commons.math4.exception.MathIllegalArgumentException",
      "org.apache.commons.math4.stat.inference.BinomialTest",
      "org.apache.commons.math4.exception.util.ExceptionContextProvider",
      "org.apache.commons.math4.exception.NullArgumentException",
      "org.apache.commons.math4.exception.util.ExceptionContext",
      "org.apache.commons.numbers.gamma.LogGamma",
      "org.apache.commons.rng.UniformRandomProvider",
      "org.apache.commons.statistics.distribution.DiscreteDistribution$Sampler",
      "org.apache.commons.math4.exception.NotPositiveException",
      "org.apache.commons.math4.exception.MathInternalError",
      "org.apache.commons.math4.stat.inference.BinomialTest$1",
      "org.apache.commons.math4.exception.MathRuntimeException",
      "org.apache.commons.numbers.core.Precision",
      "org.apache.commons.numbers.gamma.LogGammaSum",
      "org.apache.commons.math4.exception.OutOfRangeException",
      "org.apache.commons.numbers.gamma.LogGamma1p",
      "org.apache.commons.math4.exception.MathIllegalNumberException",
      "org.apache.commons.statistics.distribution.BinomialDistribution",
      "org.apache.commons.numbers.gamma.LogBeta",
      "org.apache.commons.numbers.gamma.RegularizedBeta",
      "org.apache.commons.math4.stat.inference.AlternativeHypothesis",
      "org.apache.commons.math4.exception.util.ArgUtils"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(BinomialTest_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.apache.commons.math4.stat.inference.BinomialTest",
      "org.apache.commons.math4.exception.util.LocalizedFormats",
      "org.apache.commons.math4.stat.inference.AlternativeHypothesis",
      "org.apache.commons.math4.stat.inference.BinomialTest$1",
      "org.apache.commons.statistics.distribution.AbstractDiscreteDistribution",
      "org.apache.commons.statistics.distribution.BinomialDistribution",
      "org.apache.commons.math4.exception.MathRuntimeException",
      "org.apache.commons.math4.exception.MathIllegalArgumentException",
      "org.apache.commons.math4.exception.MathIllegalNumberException",
      "org.apache.commons.math4.exception.OutOfRangeException",
      "org.apache.commons.math4.exception.util.ExceptionContext",
      "org.apache.commons.math4.exception.util.ArgUtils",
      "org.apache.commons.math4.exception.NumberIsTooSmallException",
      "org.apache.commons.math4.exception.NotPositiveException",
      "org.apache.commons.numbers.gamma.RegularizedBeta",
      "org.apache.commons.numbers.fraction.ContinuedFraction",
      "org.apache.commons.numbers.gamma.RegularizedBeta$1",
      "org.apache.commons.numbers.gamma.LogBeta",
      "org.apache.commons.numbers.gamma.LogGamma",
      "org.apache.commons.numbers.gamma.LogGamma1p",
      "org.apache.commons.numbers.gamma.InvGamma1pm1",
      "org.apache.commons.numbers.gamma.LogGammaSum",
      "org.apache.commons.numbers.core.Precision",
      "org.apache.commons.statistics.distribution.SaddlePointExpansionUtils",
      "org.apache.commons.math4.exception.NullArgumentException",
      "org.apache.commons.statistics.distribution.DistributionException"
    );
  }
}
